sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t tijanasutara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tijanasutara/docker-react npm run test -- --coverage

