version: '3'

services:
  web:
    build: 
      context: . # folder gde su dockerfajlovi
      dockerfile: Dockerfile.dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - C:\Users\sutar00t\Desktop\docker\react-app\frontend:/app
  tests:
    build: 
      context: . # folder gde su dockerfajlovi
      dockerfile: Dockerfile.dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - C:\Users\sutar00t\Desktop\docker\react-app\frontend:/app
    command: ["npm", "run", "test"]